package nu.wasis.geotracker.model;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here

import android.location.Location;
// KEEP INCLUDES END
/**
 * Entity mapped to table GEO_LOCATION.
 */
public class GeoLocation implements nu.wasis.geotracker.model.DomainObject {

    private Long id;
    private double latitude;
    private double longitude;
    private Double altitude;
    private Float accuracy;
    private Float speed;
    private Long time;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public GeoLocation() {
    }

    public GeoLocation(Long id) {
        this.id = id;
    }

    public GeoLocation(Long id, double latitude, double longitude, Double altitude, Float accuracy, Float speed, Long time) {
        this.id = id;
        this.latitude = latitude;
        this.longitude = longitude;
        this.altitude = altitude;
        this.accuracy = accuracy;
        this.speed = speed;
        this.time = time;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public double getLatitude() {
        return latitude;
    }

    public void setLatitude(double latitude) {
        this.latitude = latitude;
    }

    public double getLongitude() {
        return longitude;
    }

    public void setLongitude(double longitude) {
        this.longitude = longitude;
    }

    public Double getAltitude() {
        return altitude;
    }

    public void setAltitude(Double altitude) {
        this.altitude = altitude;
    }

    public Float getAccuracy() {
        return accuracy;
    }

    public void setAccuracy(Float accuracy) {
        this.accuracy = accuracy;
    }

    public Float getSpeed() {
        return speed;
    }

    public void setSpeed(Float speed) {
        this.speed = speed;
    }

    public Long getTime() {
        return time;
    }

    public void setTime(Long time) {
        this.time = time;
    }

    // KEEP METHODS - put your custom methods here

    public GeoLocation(Location l) {
        this(null, l.getLatitude(), l.getLongitude(), l.getAltitude(), l.getAccuracy(), l.getSpeed(), l.getTime());
    }
    // KEEP METHODS END

}
